
name: download

on:
  push:
    branches: [ master ]
  watch:
    types: started
  schedule:
    - cron: "0 7 * * *"

jobs:
  UpdateReadme:
    runs-on: ubuntu-latest
    steps:
      - name: 'Download Readme'
        uses: actions/checkout@v2
      - name: 'setup python'
        uses: actions/setup-python@master
        with: 
          ptrhon-version: 3.8
      - name: 'Commit'
        id: 'commit'
        run: |
          pip3 install -r requirements.txt
          python3 pixiv.py ${{ secrets.P_A_TOKEN }} ${{ secrets.P_R_TOKEN }} -r
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -am 'Update'
          echo ::set-output name=status::success
       
      - name: 'GitHub Push'
        if: steps.commit.output.status != 'success'
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
        
