name: gen_readme

on:
  watch:
    types: started
  schedule:
    - cron: "20 8 * * *"

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: 'gen_readme'
        uses: actions/checkout@v2
      - name: 'setup python'
        uses: actions/setup-python@master
        with: 
          python-version: 3.8
      - name: 'Commit'
        id: 'commit'
        run: |
          rm -rf ./README.md
          python gen_readme.py
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -am 'Update'
          echo ::set-output name=status::success
       
      - name: 'GitHub Push'
        if: steps.commit.output.status != 'success'
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
