name: upload_github

on:
#   push:
#     branches: 
#       [ master ]
  schedule:
    - cron: "0 9 * * *"

jobs:
  upload_github:
    runs-on: ubuntu-latest
    steps:
      - name: 'upload_github'
        uses: actions/checkout@v2
      - name: 'setup python'
        uses: actions/setup-python@master
        with: 
          python-version: 3.8
      - name: 'Commit'
        id: 'commit'
        env: 
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          REMOTE_REPO: ''
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub
          python upload_github.py $ACCESS_TOKEN
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -am 'Update'
          echo ::set-output name=status::success
      - name: 'GitHub Push'
        if: steps.commit.output.status != 'success'
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
