name: upload_github

on:
  push:
    branches:
      [ master ]
  schedule:
    - cron: "0 9 * * *"

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: 'upload_github'
        uses: actions/checkout@v2
      - name: 'setup python'
        uses: actions/setup-python@master
        with: 
          python-version: 3.8
      - name: 'Commit'
        id: 'commit'
        env: 
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub
          python upload_github.py 
